### ISSUE TITLE
date not properly being checked

### ISSUE THREAD

**Issue by evilsecurity** [brandon-rhodes/pyephem#107]
#### Nice work with the Ephem , lets consider this example code

``` python
j = ephem.Jupiter()
 j.compute('1986/2/8')//  The compute is taking the date in an order like year/month/date 
 print (j.earth_distance)
```
- but the date is not checking for format or either checking for wrong inputs and yet yeilding results.
  like an input like 
- compute('00/67/67')  is still generating a result een though there is no possiblity of 00 year and a 67 month or either a 67 date ..
- This isnt a serious security issue or so, but still wanted to know if this is being changed since i am using Ephem in one of my projects

**Comment by evilsecurity** [comment]
I just wanted to know , was this issue being looked at or this is not being considered an issue ?
so that i can close this off

Regards
Anonymous

**Comment by brandon-rhodes** [comment]
I am currently attending PyCon 2016 and it will be another week or two before I can tackle my backlog of GitHub issues. I will look at it then!

**Comment by brandon-rhodes** [comment]
Now that I have a few minutes to look at this: what is the security issue that you are proposing? First, there is no problem with year zero, because astronomers ignore BC and instead number years backwards from AD 1 as years 0, -1, -2, and so forth. Second, so long as the date routine returns a float, the astronomy routines should be able to make some sort of sense of the value.

The goal of this library is to behave roughly the same as the XEphem graphical application. It accepts malformed date strings and tries to do its best with them. If you want to pursue this issue, please find a difference between the way that XEphem handles a given date string and the way that PyEphem handles it. Thanks!

**Comment by brandon-rhodes** [comment]
I am going to close this for now, but will watch the issue in case you can provide more details. Thanks!
