### ISSUE TITLE
add phase angle attribute for solar system bodies

### ISSUE THREAD

**Issue by migueldvb** [brandon-rhodes/pyephem#11]
It would be useful to have a solar phase angle attribute (angle between Sun-body-observer) for Solar System objects.

**Comment by ysBach** [comment]
May I ask if this functionality is added? 
This will have enormous advantage to people like me (we need to find targets which will be at near 0 or near 100 degree phase angle for many purposes, and querying ~ all asteroids to JPL/HORIZONS is almost impossible).

Currently I am using solar elongation to find candidates with near 0 phase angle (``object.elong > 170`` for example), but I have no idea how to make candidate list which will be at near 100 degree phase angle .

**Comment by drbitboy** [comment]
@ysBach Where do you find the ephemerides for the candidates to test?  Because if you had ephemerides in [SPICE](http://naif.jpl.nasa.gov/) format, you could use the SPICE toolkit, specifically [GFILUM](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/gfilum_c.html), to find the time when phase angles are in a given range.

HORIZONS has the capability to return candidates' ephemerides as SPICE kernels, and access to HORIZONS can also be automated (cf. telnet horizons.jpl.nasa.gov).

**Comment by brandon-rhodes** [comment]
As the solar phase angle is (a) not returned by the C library "libastro" that PyEphem is a wrapper around, and (b) not easily computed since PyEphem returns angles instead of vectors, I am going to close this issue as impractical. I encourage folks to try out Skyfield, a library based on vectors that should make calculations like this more feasible. Thanks!
