### ISSUE TITLE
Perturbations

### ISSUE THREAD

**Issue by harmonmi** [brandon-rhodes/pyephem#113]
I'm recently working on computing access to targets on Earth from a satellite. I found pyephem to be the best resource for doing so (from the programming perspective), but I have a question in regards to discrepancies between pyephem and STK results.

Example problem:
Given some orbit defined by standard keplerian elements and some sensor on the satellite which has a cone half-angle of 5 degrees (pointing straight down) of visibility ... find the periods of time in which targets are visible to the sensor. It correctly calculates the amount of accesses, but the time ranges have errors in the degree of seconds. With STK, I am including perturbation (J4/J2); does pyephem account for any perturbations? If not, could this be where the error is coming from? I'm still not quite familiar yet with all of the ins-and-outs of orbit determination so I don't know the scale of the error that could be generated by different propagators.

Example output from STK (Start -> Stop):
Target 1) 2016/11/10 04:03:33    2016/11/10 04:03:48
Target 2) 2016/11/11 07:06:59    2016/11/11 07:07:21

Example output from pyephem using same orbital elements (Start -> Stop):
Target 1) 2016/11/10 04:03:31    2016/11/10 04:03:50
Target 2) 2016/11/11 07:06:43    2016/11/11 07:07:04

As you can see the times are a bit off, both in terms of start/end time and total access duration. Any suggestions/information you can give me as to why the error exists?

**Comment by drbitboy** [comment]
Have the two methods (STK) print out their state (6-element position+velocity) vectors for the satellite.  Simple math from there should allow you to assess the dTime/dOrbit.

Btw, the SPICE geometry finder routines solve your example problem in one line of code (with another few dozen for I/O, plus some non-trivial but straigtforward configuration steps).  See ftp://naif.jpl.nasa.gov/pub/naif/toolkit_docs/IDL/cspice/gfpa_c.html

**Comment by brandon-rhodes** [comment]
PyEphem is based on `libastro` which has a somewhat old implementation of SGP4 that does not agree in all details with the most up-to-date implementations. If you want close agreement with other modern tools, I recommend trying out Skyfield:

http://rhodesmill.org/skyfield/

which uses my recent adaption of SGP4 to Python:

https://pypi.python.org/pypi/sgp4/

Of course, results can still differ by several seconds, because SGP4 is in the best case only accurate to within a few kilometers, I'm told, so different solvers can be off my many seconds from each other. Once you get a rough estimate from an SGP4 implementation, you will then need hardware on the satellite or at the ground station that locks in more precisely to wherever the satellite actually winds up appearing!

I am going to close this issue, as I am not planning any modifications to `libastro`, because then PyEphem's predictions would stop agreeing with XEphem's predictions, which it's trying to imitate. Feel free to open an issue over on Skyfield's GitHub page if you encounter any problems! (Other than the fact that its pure-Python SGP4 is pretty slow, which I hope will improve after the holidays.)
