### ISSUE TITLE
Building for python 3.6 fails

### ISSUE THREAD

**Issue by sizzzzlerz** [brandon-rhodes/pyephem#118]
On Linux, building and installing with python3, v3.6 does not produce a library file with the expected name **_libastro.so** as it does with python 2,7.12. Instead, the library is named  **_libastro.cpython-36m-c86_64-linux-gnu.so**. Obviously, when importing ephem into python3, an exception is raised because it can't find the library file. If I manually create a soft link to the library in the installation directory, it gets imported and everything works as expected.

**Comment by brandon-rhodes** [comment]
That extension is the normal one for Python 3.6 and should not cause a problem. I think the problem might be that you are sitting in the PyEphem source directory, so that the `ephem/` directory sitting first on your past is the raw source one that does not have the compiled library at all. Could you try running Python from a different directory and see if that fixes it?

**Comment by brandon-rhodes** [comment]
@sizzzzlerz I am going to close this for now to keep my board clear, but if you do get the chance to try the experiment that I suggested, then simply come back here and re-open the issue.
