### ISSUE TITLE
pip install fails on Windows 10

### ISSUE THREAD

**Issue by gboysen** [brandon-rhodes/pyephem#120]
Well after using it in Windows 7 I have to up-grade to Windows 10 and cannot get past the pip in stall 

    c:\users\boysengunnar\appdata\local\programs\python\python36-32\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\14.0\\VC\\bin\\cl.exe' failed with exit status 2

**Comment by brandon-rhodes** [comment]
I do not have access to Windows 10 at the moment, but the error seems to be between Python's header files and the Windows header files, so before trying to compile a complex program like PyEphem you might try compiling a simple "Hello world" program that imports `pyconfig.h` and see if you can get that working before trying PyEphem again?

A Google search for `"pyconfig.h" "io.h"` turns up several Stack Overflow questions that you might also dive into. If you are able to track down the problem to PyEphem itself, do provide more details; or if you find it's a problem with all C compilation of Python on your system, then let us know here if you find a fix in case anyone else runs into the problem. Thanks!

**Comment by gboysen** [comment]
Thank you for your replay i got it to work but so. or remember how. All the stuck overflow did not work. I think i downloaded the girl and used "sudo pip install file " 
I have a look later tonight.

**Comment by gboysen** [comment]
Well other windows 10 same issue.
Successfully run pip install ephem and pip install pyephem
pip list shows both.
import ephem give erroe no such module
>>> print(sys.path)
['', 'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python35-32\\Lib\\idlelib', 'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python35-32\\python35.zip', 'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python35-32\\DLLs', 'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python35-32\\lib', 'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python35-32', 'C:\\Users\\sebas\\AppData\\Local\\Programs\\Python\\Python35-32\\lib\\site-packages'] 
.
Why are there "\\" I wonder.

**Comment by brandon-rhodes** [comment]
The `\` backslashes are there because that's how Windows delimits directories.

So you successfully ran pip install, but Python cannot find the resulting module? I wonder whether your `pip` command and `python` command are both the exact same Python install or not? Can you ask the operating system what command in what folder is getting run when you type `pip` and then when you type `python`? Sometimes I have had the problem that `pip` is writing packages into one version of Python on my hard drive, while `python` is invoking the interpreter of an entirely different copy of Python somewhere else on my hard drive.

**Comment by gboysen** [comment]
Thank you i actually figured it all out.

It is all about file location. Pip in windows 10 only runs when called in the right folder.
I have not tried to add the ...\...\python\Scripts, where pip is, to the environment variable, since now i know how to use it now.
On my raspberry pi pip run from all folders.
I will update the blog/forum accordingly.
Also if python 2 and 3 are installed using pip3 has be used. 
.
Thank you! We have a lot fun with ephem. Not sure the difference between ephem and pyephem.
The goal is to built a tracking system for our telescope. We got the ephem worked out and are currently working with gyro/acel sensor to learn how to determine current orientation! 
.
Thank you.

**Comment by brandon-rhodes** [comment]
Thanks for the update, I am glad you got it working. And thanks for the description of your project, it is always fun to hear what users are using PyEphem for!

**Comment by gboysen** [comment]
Well I got an Windows 10 image form work and are back to square 1 with
installing pyephem.
I'll try to keep better notes this time.
-Installed python 3.6.2 with IDLE
-pip is included and is at location in ...Programs\Python\Python36-
32\Scripts
-!pip install pyephem returns  --single-version-externally-managed
--compile" failed with error code 1
                 !!   running command prompt normal or administrator = same
erorr.
-!Copied pip into the folder contain python -> same error
-download 32 and 64 bit wheels did work either
-error pyephem-3.7.6.0-cp34-none-win32.whl is not a supported wheel on this
platform.
.
Then is run command prompt as administrator again and it worked
Yahhh...

C:\Users\BoysenGunnar\AppData\Local\Programs\Python\Python36-32\Scripts>pip
install pyephem
Collecting pyephem
  Using cached pyephem-3.7.6.0.tar.gz
Installing collected packages: pyephem
  Running setup.py install for pyephem ... done
Successfully installed pyephem-3.7.6.0

C:\Users\BoysenGunnar\AppData\Local\Programs\Python\Python36-32\Scripts>

**Comment by brandon-rhodes** [comment]
Thanks for the more detailed notes!

**Comment by sergeod9** [comment]
Same problem here, I've been fiddling with the environment variables for the last couple of hours, the problem is with io.h file in VS C++, for some reason pip can't find it, even when added to the path in the system environment variables

**Comment by gboysen** [comment]
I know I figured it out and have since then installed and run it on several Windows 10 PCs. I though i posted a solution if not let me know and i did it out.

**Comment by sergeod9** [comment]
Could you please provide a link to the solution, I tried everything  I
could find on the forums, nothing worked so far.

On 17 Nov 2017 7:25 am, "gboysen" <notifications@github.com> wrote:

I know I figured it out and have since then installed and run it on several
Windows 10 PCs. I though i posted a solution if not let me know and i did
it out.

Sent from my iPhone

> On Nov 16, 2017, at 12:19 PM, Georges Dahdouh <notifications@github.com>
wrote:
>
> Same problem here, I've been fiddling with the environment variables for
the last couple of hours, the problem is with io.h file in VS C++, for some
reason pip can't find it, even when added to the path in the system
environment variables
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/brandon-rhodes/pyephem/issues/120#issuecomment-345142060>,
or mute the thread

**Comment by gboysen** [comment]
damn I had a screen free weekend ping me later tonight I am in CST.
