### ISSUE TITLE
New pip version?

### ISSUE THREAD

**Issue by ppapadeas** [brandon-rhodes/pyephem#150]
Hey @brandon-rhodes !

Any chance that a new version will be tagged and pushed as a package to pipy?
We are using pyephem extensively in SatNOGS (https://satnogs.org https://network.satnogs.org) and would like to get the latest fixes especially the solution to #63 .

Thanks!

**Comment by brandon-rhodes** [comment]
The machines I used to have set up to allow Windows, Mac, and Linux builds are long since decommissioned, so I currently don't have a good way to do releases — and with most of my effort going towards Skyfield, I hadn't necessarily planned on another release. But just a few weekends ago at PyBay, someone I spoke to was also wondering if another release could happen.

So let's see if anyone has time to contribute any Travis YAML and Appveyor YAML adjustments needed, along with a release README, that sets up builds of wheels on Windows, Mac, and Linux, and then has instructions for pushing all of those compiled artifacts up to PyPI. If someone interested will put that together, I'll be happy to make another release — and, once I'm confident in the process, I might also share with them PyPI access to the project so that other folks besides me can make releases.

If I remember who asked me, I'll @ them here in this issue to gauge whether they're still interested.

**Comment by brandon-rhodes** [comment]
(Was it you, @MartyMacGyver?)

**Comment by MartyMacGyver** [comment]
It was indeed! Things got busy after PyBay but I've been wondering if there's a way to leverage Appveyor (or similar) for this.

**Comment by kerel-fs** [comment]
Hi!
I've just built a working CI for the deployment of python-satellitetle to PyPI using gitlab-CI, see https://gitlab.com/kerel-fs/python-satellitetle/merge_requests/2
Maybe you can use this as a reference.

Unfortunately I've no experience in AppVeyor yet. Here is a guide how to use AppVeyor CI for testing&building python packages on windows: https://packaging.python.org/guides/supporting-windows-using-appveyor/

Thanks for your great projects btw!

**Comment by adamkalis** [comment]
There is a new release, v3.7.7.0 which includes the fix of #63 and the rest until recently, so I guess @brandon-rhodes you could close this issue.

**Comment by brandon-rhodes** [comment]
@adamkalis Oh, thanks for pointing out that this old issue was indeed resolved by that new release! Closing —

**Comment by MartyMacGyver** [comment]
I just wanted to say thanks for publishing this - I'm still using pyephem and having an updated version that's also easy for people to install is a boon.

**Comment by brandon-rhodes** [comment]
You're welcome, @MartyMacGyver! To give full credit, it was this project that made it possible for me to get a new build process going, so star their project if you're interested in highlighting its impact:

https://github.com/joerick/cibuildwheel
