### ISSUE TITLE
cities.lookup() no longer works because Google now requires API key

### ISSUE THREAD

**Issue by YuMan-Tam** [brandon-rhodes/pyephem#156]
The function ```cities.lookup(address)``` no longer works. For any input ```address```, the output from the source code ```data = json.loads(urlopen(url).read().decode('utf-8'))``` is:

``` {'error_message': 'Keyless access to Google Maps Platform is deprecated. Please use an API key with all your API calls to avoid service interruption. For further details please refer to http://g.co/dev/maps-no-account', 'results': [], 'status': 'OVER_QUERY_LIMIT'}```

Besides modifying ```cities.lookup(address)``` to something like ```cities.lookup(address, API_key)```, I wonder if there's any plan in the next release to address the issue?

Thank you!

**Comment by drbitboy** [comment]
Am I missing something, or does fixing this require a credit card?

**Comment by brandon-rhodes** [comment]
No plan is in place — thanks for being the first one to report this?

Before we think of requiring an API key, are there other sources of this data from some of the more public mapping projects?

**Comment by barrycarter** [comment]
I use Google Maps API and can confirm they started requiring key use in mid-September. Some APIs won't work at all without a key-- if you try to display a map, the map will be faded with a very prominent "FOR DEV USE ONLY" watermark.

To get a key, you do need a credit card, but 1) they promise not to charge it without your explicit permission, and 2) you can use a virtual card with a very low limit (eg, $1). However, I don't think this is helpful here, since any "public" API key would get used up too quickly.

I suggest using geonames.org (or possibly openstreetmap.org) as a good open source replacement.

**Comment by vauSoftTech** [comment]
> No plan is in place — thanks for being the first one to report this!
> 
> Before we think of requiring an API key, are there other sources of this data from some of the more public mapping projects?

WikiData project has Lat & Long for almost all the cities around the world.

**Comment by brandon-rhodes** [comment]
@vauSoftTech — Thanks for pointing out a possible alternative source of data. (Do you happen to have a snippet of example Python code that can take a city name and using WikiData, return its coordinates?)

**Comment by vauSoftTech** [comment]
> @vauSoftTech — Thanks for pointing out a possible alternative source of data. (Do you happen to have a snippet of example Python code that can take a city name and using WikiData, return its coordinates?)

I do not anything ready, but can certainly try to come-up with a small code sample.
