### ISSUE TITLE
Need a version for python 3!

### ISSUE THREAD

**Issue by GlenLangston** [brandon-rhodes/pyephem#167]
Hi Brandon,

Thanks for all your effort of creating pyephem.

It has been very useful to many of us for radio astronomy projects.

We're being forced into python3 land and I do not see an easy path from
pyephem to skyfield.   

For instance there does not seem to be an "Observer()" member in skyfield.
It would be great if you (or someone with some knowledge) could create a python3 
compatible version of pyephem.

If not, a mapping of pyephem.Observer() to skyfield.?? would be a great help.

Thanks
Glen

our code is at GitHub.com/glangsto/analyze and
GitHub.com/WVURAIL/gr-radio_astro

**Comment by brandon-rhodes** [comment]
> Thanks for all your effort of creating pyephem.  It has been very useful to many of us for radio astronomy projects.

You're welcome! I'm always happy to learn about a real-life field like radio astronomy that has been able to use one of my libraries. Wow!

> We're being forced into python3 land and I do not see an easy path from pyephem to skyfield.

That's understandable — existing code is a big investment and it rarely makes sense to replace it.

> For instance there does not seem to be an "Observer()" member in skyfield.

The class has the name `Topos` (think "topocentric") in Skyfield. Here’s some example code showing how it is used:

https://rhodesmill.org/skyfield/examples.html#at-what-angle-in-the-sky-is-the-crescent-moon

> It would be great if you (or someone with some knowledge) could create a python3 compatible version of pyephem.

Happily, PyEphem has been compatible with Python 3 since 2015. Should I add some documentation, or a chart, to PyEphem’s front page stating which Python versions it supports? Or is there somewhere else you looked for that info and didn’t find it, that I could fix?

**Comment by brandon-rhodes** [comment]
(Am going to close this as it looks like the issue went quiet, and since PyPI's new design advertises PyEphem's Python compatibilities right on the front page:

https://pypi.org/project/ephem/

So it looks like the version matrix in `setup.py` is now clearly advertised to users, which I hope solves the problem!)
