### ISSUE TITLE
Astrometric Topocentric Postition for non-Earth satellites?

### ISSUE THREAD

**Issue by Lyalpha** [brandon-rhodes/pyephem#168]
Hopefully this issue makes sense, but if it is flawed, please let me know.

I am interested in matching detections to minor solar system bodies. This is by using an `xephem` database of their orbit elements (from Minor Planet Center), propagating them to the epoch of my observation with `pyephem`, and then cross matching to my detections.

Running a comparison of pyephem `a_ra`, `a_dec` coordinates with those produced by the MPC geocentric positions produces a good match, within an arcsecond for the vast majority - so the 2-body propagation is sufficient.

However, when comparing `pyephem` positions to actual detections, I have found a few arcsecond offset is typical. This offset is closely matched to the offset I find between `pyephem` and MPC observatory positions (i.e. asking MPC to give ra/dec for the observatory's location, not geocentric).

I believe that some parallax effect is likely to be the cause for this discrepancy in this case? Since `pyephem` positions are geocentric but the actual detections are subject to a parallax from this position due to our topocentric position. 

If the above indeed appears correct, is there any way to obtain the *Astrometric Topocentric Postition* for a solar-system body? From reading https://rhodesmill.org/pyephem/radec.html the apparent positions are not what I am interested in (since I have star-atlas positions for my detections), and the astrometric topocentric position is only available for Earth satellites.

Many thanks for the great package and do let me know if it is possible to be using `SkyField` at this point for this work (I see some activity related to orbits recently.)

**Comment by brandon-rhodes** [comment]
> If the above indeed appears correct, is there any way to obtain the Astrometric Topocentric Postition for a solar-system body?

No. The underlying `libastro` library that PyEphem is a wrapper around does not, if I recall, provide a way to combine the concept of "topocentric" with "astrometric" because it hard-wires the order in which the operations are applied.

This week I am planning on adding minor planet support to the Skyfield library that I wrote when I wanted to move beyond `libastro` limitations like this:

https://rhodesmill.org/skyfield/

Its front page shows how to generate an astrometric topocentric position — check out the second code example. Once I release a new version that supports minor planets, you will be able to use a minor planet in that example instead.

**Comment by brandon-rhodes** [comment]
I'll wait to close this issue until Skyfield can propagate MPC orbits.

**Comment by brandon-rhodes** [comment]
Oh, I should have returned to this issue earlier: Skyfield can indeed now propagate MPC orbits, and as mentioned above, it will support the generation of the desired coordinates, so I'm closing this issue now. Open a discussion or issue over in the Skyfield repository if anything goes wrong; hopefully it will work on your first try!
