### ISSUE TITLE
Unexpected results between Python 2 and Python 3

### ISSUE THREAD

**Issue by funxiun** [brandon-rhodes/pyephem#172]
Hi

While creating a script for getting moon phase information I stumbled upon this weird problem.
In Python 2.7 I've got a time and date returned for the next full moon:

```
Python 2.7.18rc1 (default, Apr  7 2020, 12:05:55) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> ephem.next_full_moon('2020/06')
2020/6/5 19:12:21
```

But in Python 3 I get this:

```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> ephem.next_full_moon('2020/06')
43986.300242368874
```

I get a floating point number returned instead of a date and time.
This also happens when I call every other emphem.next_... function.
ephem.now() gives also a floating point number.

Easiest way is to stick with Python 2 but that is EOL.

**Comment by brandon-rhodes** [comment]
Thanks for letting me know! Could you display for us the result of calling `type()` on each of those values? Actually, three results would be helpful: the `type()`, the `str()`, and the `repr()` of each one. Maybe you could put them in a tuple together:
```
>>> value = …
>>> print((type(value), str(value), repr(value)))
```
That should get us closer to an answer about what's going on.

**Comment by funxiun** [comment]
Hi Brandon

That's quick! :-)

Here are the results:

```
Python 2.7.18rc1 (default, Apr  7 2020, 12:05:55) 
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> value=ephem.next_full_moon('2020/05')
>>> print((type(value), str(value), repr(value)))
(<type 'ephem.Date'>, '2020/5/7 10:45:11', '43956.948048116246')

```
```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> value=ephem.next_full_moon('2020/05')
>>> print((type(value), str(value), repr(value)))
(<class 'ephem.Date'>, '2020/5/7 10:45:11', '43956.948048116246')
```

**Comment by brandon-rhodes** [comment]
Thanks for that output! I am looking over the C code that implements that object. One last check: under Python 3, what does `print()` of the value show? In the docs, I see several examples of values being printed, but I'm not sure I see guarantees about what will display at the raw prompt, so this might be a behavior that PyEphem hasn't made promises about? I'm still reading code and will probably need to read up on differences between Python 2 and Python 3 to be sure about what's changed.

**Comment by funxiun** [comment]
No problem at all. Happy to help.

This is the output under Python 3:

```
Python 3.8.2 (default, Apr 27 2020, 15:53:34) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ephem
>>> value=ephem.next_full_moon('2020/05')
>>> print (value)
2020/5/7 10:45:11

```

**Comment by brandon-rhodes** [comment]
So, the difference seems to involve the type object for `Date`. Here's the relevant C code:
```
static PyTypeObject DateType = {
     PyVarObject_HEAD_INIT(NULL, 0)
     "ephem.Date",
     sizeof(PyFloatObject),
     0,
     0,				/* tp_dealloc */
     Date_print,		/* tp_print */
     0,				/* tp_getattr */
     0,				/* tp_setattr */
     0,				/* tp_compare */
     0,				/* tp_repr */
     0,				/* tp_as_number */
     0,				/* tp_as_sequence */
     0,				/* tp_as_mapping */
     0,				/* tp_hash */
     0,				/* tp_call */
     Date_str,			/* tp_str */
     ...
```
It looks like under Python 2, having a `tp_str` was enough to control the `repr()` string that Python prints at its prompt. Presumably the floating-type object that the `Date` inherits from had a `tp_repr` that called its `tp_str`, so that replacing the latter also reprogrammed the behavior of the former.

But in Python 3, the float must no longer have a `tp_repr` that calls `tp_str`. (Or else the language itself makes different underlying calls and the float object is not involved?)

If I go in and change the line to:
```
     Date_str,			/* tp_repr */
```
and recompile, then under Python 3 the library starts behaving exactly as it does under Python 2.

So: we know how to make the two versions agree if we need to.

What I'm not clear on is what the consequences would be of making the change. At this point my impression is that PyEphem has many Python 3 users, whose scripts might at this point depend on the `str()` of a date showing the calendar components and the `repr()` of a date showing the underlying floating point number.

The big question is: do any such scripts really exist?

If folks have come to depend on the new behavior, then it can’t change without breaking their scripts, and would probably have to remain in place forever. We would simply have to encourage people to use `print()` to see the "pretty" formatting for a date.

If on the other hand we could guarantee that no existing scripts cared about the `repr()` of a Date, we could make the change in perfect safety.

I'm pessimistic about being able to make such a guarantee, alas.

Does that make sense given the behaviors you have seen under both languages?

**Comment by funxiun** [comment]
I understand the problem and I would agree if you didn't roll out this fix.
Indeed, it has a big chance breaking scripts and it isn't a real show-stopper because it has a simple workaround.
Thanks for investigating this and keep up the good work!

**Comment by brandon-rhodes** [comment]
Thanks again for the report, though! Hopefully this issue will come up in a search if anyone else sees the difference in the future. The next time I'm in the docs I'll think about adding something, but I'm not sure where it would go that folks would be likely to run across it when they need it. We'll see!
