### ISSUE TITLE
pip install pyephem ... installs the old version

### ISSUE THREAD

**Issue by aendie** [brandon-rhodes/pyephem#180]
If I'm correct, ephem and pyephem should be synonymous, i.e. the same installation. However "pip install pyephem" gives you 3.7.7.0 and a subsequent "pip install ephem" doesn't upgrade it, However on a totally new Python3 installation "pip install ephem" will correctly install 3.7.7.1

TESTING: On Python 3.9.0 I first installed pyephem:

```
C:\Python39>pip install pyephem
Collecting pyephem
  Using cached pyephem-3.7.7.0.tar.gz (1.3 kB)
Collecting ephem==3.7.7.0
  Downloading ephem-3.7.7.0.tar.gz (745 kB)
     |████████████████████████████████| 745 kB 1.6 MB/s
Building wheels for collected packages: pyephem, ephem
  Building wheel for pyephem (setup.py) ... done
  Created wheel for pyephem: filename=pyephem-3.7.7.0-py3-none-any.whl size=1468 sha256=9e02acd867d52cfecda95733f01bdfafac346c8971fb7d62027a92a7e631095c
  Stored in directory: c:\users\andrew\appdata\local\pip\cache\wheels\b3\8f\c5\ba290e989b3144863e9a64d185bceac241ab2ddab27abc64f8
  Building wheel for ephem (setup.py) ... done
  Created wheel for ephem: filename=ephem-3.7.7.0-cp39-cp39-win_amd64.whl size=821628 sha256=3806f0241c24f6b1bf5e25c7a9c85bb6eb0f15e29a55f1b1c033d288e6d81c08
  Stored in directory: c:\users\andrew\appdata\local\pip\cache\wheels\c9\65\3e\9a94debb4fc7866d74e72529a32fadc54197e88b3cc0222cfb
Successfully built pyephem ephem
Installing collected packages: ephem, pyephem
Successfully installed ephem-3.7.7.0 pyephem-3.7.7.0

C:\Python39>

```

I was unable to update it to 3.7.7.1 once I saw it was a lower version:

```
C:\Python39>pip install ephem
Requirement already satisfied: ephem in c:\python39\lib\site-packages (3.7.7.0)

C:\Python39>pip uninstall pyephem
Found existing installation: pyephem 3.7.7.0
Uninstalling pyephem-3.7.7.0:
  Would remove:
    c:\python39\lib\site-packages\pyephem-3.7.7.0.dist-info\*
Proceed (y/n)? y
  Successfully uninstalled pyephem-3.7.7.0

C:\Python39>pip install ephem
Requirement already satisfied: ephem in c:\python39\lib\site-packages (3.7.7.0)

```

However, after a clean Python3 reinstall I got the latest version of ephem (without pyephem) via "pip install ephem":

```
C:\Python39>pip install ephem
Collecting ephem
  Downloading ephem-3.7.7.1.tar.gz (745 kB)
     |████████████████████████████████| 745 kB 2.2 MB/s
Building wheels for collected packages: ephem
  Building wheel for ephem (setup.py) ... done
  Created wheel for ephem: filename=ephem-3.7.7.1-cp39-cp39-win_amd64.whl size=822378 sha256=f19671d4ebd94c746ee11e67e5442e31ce651b739321eeeacfec0916788c41b1
  Stored in directory: c:\users\andrew\appdata\local\pip\cache\wheels\46\b0\6b\1d2fe1bd4ba45954b0f68f0ccc8b45c8f40463974468f66757
Successfully built ephem
Installing collected packages: ephem
Successfully installed ephem-3.7.7.1

C:\Python39>
```

Now I thought that "pip install pyephem" would see that 3.7.7.1 is the latest version. Unfortunately no ...

```
C:\Python39>pip install pyephem
Processing c:\users\andrew\appdata\local\pip\cache\wheels\b3\8f\c5\ba290e989b3144863e9a64d185bceac241ab2ddab27abc64f8\pyephem-3.7.7.0-py3-none-any.whl
Processing c:\users\andrew\appdata\local\pip\cache\wheels\c9\65\3e\9a94debb4fc7866d74e72529a32fadc54197e88b3cc0222cfb\ephem-3.7.7.0-cp39-cp39-win_amd64.whl
Installing collected packages: ephem, pyephem
  Attempting uninstall: ephem
    Found existing installation: ephem 3.7.7.1
    Uninstalling ephem-3.7.7.1:
      Successfully uninstalled ephem-3.7.7.1
Successfully installed ephem-3.7.7.0 pyephem-3.7.7.0

C:\Python39>

```

I know this is painfully old and I don't know if there's a good reason for this behaviour ... however, methinks (an expression used at least 150 times by William Shakespeare) that there's a spanner in the works somewhere here. I hope you agree <smile>.

P.S. I'm still using PyEphem partly for planet magnitudes (which I see you added in Skyfield 1.27 - I will look into this) and partly for speed because Skyfield (almanac.find_discrete) is slow. I believe I once mentioned this in an old email to you.

**Comment by brandon-rhodes** [comment]
> If I'm correct, ephem and pyephem should be synonymous…

The `pyephem` package has never been upgraded beyond 3.7.7.0, which depends on `ephem` of the exact same version. If it will help your project migrate, I can release a new `pyephem` that depends on the more recent version of `ephem` itself.

> …a subsequent "pip install ephem" doesn't upgrade it

That's a property of pip, yes, it does not do extra work that is not required by options on the command line. If the currently installed version is insufficient, you can tell `install` that you don't just want an install, but want an install of the very latest version, by providing `--upgrade`:

https://pip.pypa.io/en/stable/development/architecture/upgrade-options/#controlling-what-gets-installed

I'm not sure what the background was of their decision for `install` to not do upgrades automatically.

> P.S. I'm still using PyEphem partly for planet magnitudes (which I see you added in Skyfield 1.27 - I will look into this)…

It's only for a few planets so far, so I wouldn't expect that it could yet replace your use of PyEphem if you use all the planets! Keep your current code for now; hopefully someday I'll have time to implement the other planets.

> …and partly for speed because Skyfield (almanac.find_discrete) is slow. I believe I once mentioned this in an old email to you.

Yes. Skyfield is higher precision, and that results in cost compared to PyEphem. (There's also cost because Skyfield is Python rather than C, separately from any precision issue.) Someday I hope to finish working out to what extent nutation accuracy can be sacrificed by normal users doing `find_discrete()` searches, and advertise a method for buying speed that way. Maybe I'll get time to tackle it this winter, when the current semester of teaching is over!

**Comment by brandon-rhodes** [comment]
There! I have released a new `pyephem` without a version pin, so it should install the latest version of `ephem` instead of an old one.
