### ISSUE TITLE
Position of Phobos and Deimos relative to Mars

### ISSUE THREAD

**Issue by atavachron33** [brandon-rhodes/pyephem#187]
Hello,

Erroneous values, always equal to 0 for x — offset, y — offset  and z — offset  for Phobos and Deimos
For other satellites it works

------------------------------------------------------------------------------------
import ephem
phobos = ephem.Phobos()
deimos = ephem.Deimos()
io = ephem.Io()
io.compute()
phobos.compute()
deimos.compute()
print(io.x,io.y,io.z)
print(phobos.x,phobos.y,phobos.z)
print(deimos.x,deimos.y,deimos.z)
-----------------------------------------------------------------------------------
result : 
-5.394711017608643 1.4410539865493774 -1.9409044981002808
0.0 0.0 0.0
0.0 0.0 0.0

Thanks for your help

**Comment by brandon-rhodes** [comment]
@atavachron33 — Thanks for pointing that out! Glancing at the code, I don't think PyEphem has ever returned non-zero x and y coordinates for Mars moons or Uranus moons. It seems to want data files that were only ever distributed with the XEphem GUI, and that are not part of libastro itself (which PyEphem is based on).

I'm not sure how to proceed because I don't know what license applies to the data files, or even exactly which data files they are. Maybe I should just delete those Moon objects so that Python doesn't automatically advertise them as present?

I'll see if I have time to look at this in the next few weeks.

**Comment by atavachron33** [comment]
This problem has been happening since 2021 I think because before it worked, I had good values ​​for these moons (Phobos and Deimos)
and it works for all other moons from other planets

Robin

**Comment by brandon-rhodes** [comment]
It used to work? Let me double-check, then. — Oh, look at that! I apparently long ago turned those data files into C files (!) that the data can load from.
```
./extensions/data/mars.1020.c
./extensions/data/saturne.1020.c
./extensions/data/uranus.1020.c
./extensions/data/jupiter.1020.c
```
So I'll have to figure out why that setup code isn't getting called. I'll let you know what I find, thanks for letting me know it recently worked!

**Comment by brandon-rhodes** [comment]
Oh, look at that. The data files `libastro` uses ran out on January 1.
```
	/* check ranges and appropriate data file */
	if (JD < 2451179.50000)		/* Jan 1 1999 UTC */
	    return (-1);
	if (JD < 2455562.5)		/* Jan 1 2011 UTC */
            dataset = & mars_9910;
	else if (JD < 2459215.5)	/* Jan 1 2021 UTC */
	    dataset = & mars_1020;
	else
	    return (-1);
```
My guess is that the above code was poorly designed, and that instead of returning 0,0,0 when the time is out of range, it should always have raised an exception explaining which dates `libastro` can support. Now that the present date and time fall into the unsupported range, I think it's important that we go ahead and make that change.

I'm not planning a release soon, but let's leave this open, and I'll plan to add exception code before the next version.

Thanks for letting me know! This open issue will also be helpful to other folks who run into this `libastro` limitation.

**Comment by atavachron33** [comment]
thanks to you

**Comment by atavachron33** [comment]
re, Hello

same problem for the moons of Uranus
Titania, Oberon , Umbriel, Ariel and Miranda

for the moment the moons of Jupiter, Saturne are not affected.

**Comment by PhilippeDev** [comment]
Hello everone,

I ran into the same problem with this simple code:
```
>>> import ephem
>>> obs = ephem.Observer()
>>> obs.date = "2020/12/31 23:59:59"
>>> phobos = ephem.Phobos(obs)
>>> deimos = ephem.Deimos(obs)
>>> str(phobos.a_ra)
'1:39:11.34'
>>> str(deimos.a_ra)
'1:39:09.90'
>>> obs.date = "2021/01/01 00:00:00"
>>> phobos = ephem.Phobos(obs)
>>> deimos = ephem.Deimos(obs)
>>> str(phobos.a_ra)
'1:39:11.83'
>>> str(deimos.a_ra)
'1:39:11.83'
```
Starting On January 1st 2021, Phobos and Deimos always have the same position for a given date and time. The same problem occurs with Uranus satellites, but everything is OK with Jupiter and Saturn.

Funny enough, I turned to pyEphem because the code from IMCCE (https://ftp.imcce.fr/pub/ephem/satel/posxy/higprec/) in Paris stopped working on January 1st, 2021 by lack of updated polynomial coefficients, but probably IMCCE and `libastro` have linked fates... I got in touch with my contact at IMCCE to see what can be done.

What I am not sure to understand however is why it continues to work for Jupiter and Saturn after January 1st, 2021. The C code of `libastro` seems to have the same limitation for Jupiter and Saturn moons in terms of dates.

**Comment by brandon-rhodes** [comment]
I have good news! A contributor in the past few weeks updated `libastro` over in the https://github.com/XEphem/XEphem project to include Moon data through 2040, so with the next release PyEphem should also have non-zero moon positions through 2040 as well. Enjoy!
