### ISSUE TITLE
Add examples of how to deal with input that is in local etc. time

### ISSUE THREAD

**Issue by jidanni** [brandon-rhodes/pyephem#189]
/usr/lib/python3/dist-packages/ephem/doc/quick.rst says:

```
local time
----------

 >>> d = ephem.Date('1997/3/9 5:13')
 >>> ephem.localtime(d)
 datetime.datetime(1997, 3, 9, 0, 13)
 >>> print(ephem.localtime(d))
 1997-03-09 00:13:00

 * The ``localtime()`` function converts a PyEphem date
   into a Python ``datetime`` object expressed in your local time zone.

```
OK, that's great. But it is often likely that the **input** is in local
time. Mention how to deal with that.
E.g.,
2021-02-16 17:32:00 Taiwan time
`    p.date -= 8 * ephem.hour #hack`
Now we can use it.

(Yes, no new features for an old package. But just please a few little tips that could be a lifesaver when using this package offline, and thus unable to "Google" for a workaround.)

**Comment by brandon-rhodes** [comment]
I worry that users in time zones that do daylight savings time, who can't use a single offset like `8`, would have difficultly applying that approach. If we want to update the docs in that direction, it might be most responsible to recommend `pytz` and the official datetime module?

**Comment by jidanni** [comment]
Yes, all I know is my solution is the most extreme hack so anything would be better.

**Comment by Bernmeister** [comment]
@jidanni For what it's worth, in writing my own applications which use both PyEphem and Skyfield, I have found it easiest to always start with the current date/time in UTC.  This allows me to compare results between the two engines and then validate against third party websites.

I agree that a user (not programmer) will typically deal with the local date/time as input and output, so I separate user I/O from the underlying engine/calculations, allowing me to test things easily.

**Comment by brandon-rhodes** [comment]
@jidanni — I've had a chance this holiday weekend to spend a bit of time on PyEphem! So I've gone in and improved its datetime handling so that instead of ignoring the timezone attached to a Python datetime, it instead detects it, and automatically does the correct conversion from the timezone to UTC:

6dcab712d840dd0ba0c7474cba9cdd0f4a721f00

So the documentation now shows an example of providing a time in a local time zone, and having PyEphem understand and use it.

Hopefully the new version of PyEphem, and the new documentation, will be released sometime this weekend.

Thanks for pointing out that PyEphem didn't have a good way to handle this common case.

**Comment by jidanni** [comment]
That's great, however I am now in aphelion in regards to this program: I.e., 10000 miles away. So maybe next year I will start using it again. (It goes in cycles.)
