### ISSUE TITLE
Need float() in  p.elevation = float(os.environ[...

### ISSUE THREAD

**Issue by jidanni** [brandon-rhodes/pyephem#199]
Not fair when using os.environ: some values need float(), some don't:

```
p = ephem.Observer()
p.lon = os.environ["lon"]
p.lat = os.environ["lat"]
p.elevation = float(os.environ["ASL"])
```
Package: python3-ephem                   
Version: 3.7.7.1-1+b3

**Comment by Bernmeister** [comment]
@jidanni I've hit a similar issue given that lat/lon and elev use strings and floats respectively.  Actually, I did read the documentation, but forgot this salient difference and got caught more times than I care to admit!  Best to work around the issue given my remarks [here](https://github.com/brandon-rhodes/pyephem/issues/200#issuecomment-818332794).

**Comment by brandon-rhodes** [comment]
Having thought about the issue a bit, I'll render the verdict that it's `elevation` that's actually behaving appropriately here, and `lat` and `lon` that are misbehaving. In Python, we always say that “explicit is better than implicit”, and so Python lacks the automatic type coercion that lets languages like awk and Javascript do `'30' + 40` and come up with an answer. Instead, Python makes you say `float()` if you want a string to become a float. This enhances readability, because you can tell if code is performing a coercion from string to float, instead of its happening invisibly (and perhaps, thus, accidentally).

So `elevation` is well-behaved and Pythonic.

Alas for `lat` and `lon`! I didn't know what I was doing when I wrote this library back in the twenty-naughts, and so they have poor behavior, and smuggle in magical unit conversion (degrees to radians) if offered a string — even worse than simply running `float()` since a whole different number comes out.

But I can't change the behavior without breaking existing programs, so it has to stay in.

But let's stop it from spreading to additional attributes, and have `elevation` stay simple and Pythonic: it wants a float in meters, it takes a float in meters.

See the Skyfield library if you want to see a re-imagined approach which is far more consistent in how units are handled, and which tries never to hide unit changes inside magical string-to-number conversions.
