### ISSUE TITLE
Add example of BEGINNING of current year, month, etc.

### ISSUE THREAD

**Issue by jidanni** [brandon-rhodes/pyephem#200]
One can easily do operations for a whole year,
```
    m.date = ephem.now()
    date2 = m.date + 365
    while m.date <= date2:
        ...
```
month, etc.

However please do document, there in ephem/doc/*.rst,
how to start at the **beginning** of the **current** year, month, day, hour, etc.

Sure, simple,
```
    m.date = "2021"
    ...
```
But alas, that's _hardwiring_ the year into the program.

Package: python3-ephem                   
Version: 3.7.7.1-1+b3

**Comment by Bernmeister** [comment]
Is this what you want?
```
#!/usr/bin/env python3
import datetime, ephem
print( ephem.Date( ( datetime.datetime.now().year, 1, 1 ) ) )
```
results in:
```2021/1/1 00:00:00```

Documentation found [here](https://rhodesmill.org/pyephem/date.html).

**Comment by jidanni** [comment]
OK, but please also document as an example, obtaining the beginning of a
year, without importing any extra modules other than ephem itself:

#!/usr/bin/env python3
import ephem
print(ephem.Date(str(ephem.now().tuple()[0])))

gives:

2021/1/1 00:00:00

**Comment by Bernmeister** [comment]
@jidanni I'm just a lowly end-user of PyEphem, so I don't have access to directly make changes.  Over the last couple of years, I have noticed the developer(s) are hard at work on the replacement of PyEphem called [Skyfield](https://github.com/skyfielders/python-skyfield) and so less time is dedicated to PyEphem.  Unless there is a critical bug uncovered, try your best to work around the situation and/or consider moving across to [Skyfield](https://github.com/skyfielders/python-skyfield) if feasible.

@brandon-rhodes Hope you don't mind jumping in with my two cents!

**Comment by jidanni** [comment]
(OK, but alas,
$ aptitude search skyfield | wc -l
0
here on Debian.)

**Comment by Bernmeister** [comment]
I'm on Ubuntu (so Skyfield is not as yet in the repository) and so to install I use PIP3:

`sudo apt-get install -y python3-pip`

then use PIP3 to install latest Skyfield (and other dependencies):

`sudo pip3 install --upgrade pip pandas skyfield`

**Comment by brandon-rhodes** [comment]
> Hope you don't mind jumping in with my two cents!

@Bernmeister — It’s definitely helpful when you jump in and offer another user help! Thank you!

> please also document as an example, obtaining the beginning of a year, without importing any extra modules other than ephem itself

@jidanni — Could you elaborate on where your requirement “without importing any extra modules” comes from — are you low on memory and have been unable to import it?

I think I will prefer for the documentation about this issue to strongly push users towards `datetime` rather than away from it, since once users see how to convert to and from `datetime`, they can then find out the answer to questions like “how to find the beginning of the year in Python” with a simple Google search. (I just tried it, and a good Stack Overflow answer came right up!) By plugging users into the strong `datetime` ecosystem, we make it easy for them to find well-known answers to well-known questions. If instead we try to write examples that don't import the standard `datetime` module, then they are trapped trying to come up with ephem-specific maneuvers for what are already solved problems in the Python ecosystem.

Also, could you provide any background on your profile image?

**Comment by jidanni** [comment]
Well Mom always gave us extra points if we were able to do self contained programs that would fail because we were offline and couldn't install that last remaining module. Plus... adding extra dependencies is a main cause of program failure years later.
E.g., the program would work, but now won't because even though we imported A (ephem) and that works with no problem, but importing B, now years later, has some problem. E.g., even `#!/usr/bin/python` needs another character added these days here on Debian. Who would have thought about that? Anyway one might be offline so cannot research how to fix it.
 Anyway, be sure to show both ways of doing it! And yes, mention the pros and cons.

**Comment by brandon-rhodes** [comment]
> Well Mom always gave us extra points if we were able to do self contained programs that would fail because we were offline and couldn't install that last remaining module.

The `datetime` module is built-in to Python and so, happily, is always available. This “batteries included” philosophy was part of Python’s early popularity, for the reasons you mention: dependencies can be surprising and inconvenient, especially when offline. To see if a module is built-in and thus safe to use in your scripts, you can check this list:

https://docs.python.org/3/library/

**Comment by jidanni** [comment]
Well... still, future users will point out "I found a way to do it without an extra import (built in or not)." So it would be best it the ephem author also documented he was aware there was a second way to do it simply with the tools he already wrote.

**Comment by brandon-rhodes** [comment]
Returning to this issue after a few months, I'm not, alas, inclined to expand PyEphem’s documentation to show a special (and, to my eyes, rather difficult-to-read) maneuver for something that Python can accomplish more simply with its Standard Library. If there are gaps where the current documentation fails to show how a Python `datetime` can be acquired from PyEphem or provided to PyEphem as an argument, then I’m more than happy to fill those gaps to make sure that conversions in both directions are properly advertised, so that folks can use standard answers from Stack Overflow to manipulate dates.
