### ISSUE TITLE
Document tying coordinates to WGS84

### ISSUE THREAD

**Issue by jidanni** [brandon-rhodes/pyephem#209]
I'm worried that you sky mappers was and us earth mappers are not exactly talking about the same coordinate systems.

So document at a certain place at a certain time e.g., the sun, will be at exactly a certain azimuth and a certain elevation *according to WGS84*.

**Comment by jidanni** [comment]
For example I'm standing at Point A looking at Mount Everest (point B) and at time C the sun is supposed to be exactly at the tip of Mount Everest. I hope it'll work. I'm using wgs84 based maps.

**Comment by brandon-rhodes** [comment]
I'm not sure whether PyEphem positions are accurate enough for the datum to make a measurable difference, but I've given the `libastro` code a thorough reading and used my interpretation to update the docs this way:

https://github.com/brandon-rhodes/pyephem/commit/8b9ea42b9b6ba860167c00e918d6898f8687c18b

Hopefully that clears things up, let me know if it leaves any lingering questions! I'm about to do a release, at which point this new verbiage should appear on the web site too.

**Comment by jidanni** [comment]
Wow,
https://en.wikipedia.org/wiki/World_Geodetic_System#1966_version
https://en.wikipedia.org/wiki/Earth_ellipsoid IERS (1989)
who would have ever guessed!

Hmmm, maybe also document
- how much difference this would be vs. grandma's house on Google Maps.

**Comment by jidanni** [comment]
Why this mentioning precision is necessary: Imagine a mirror on a
mountain. One wants to aim it precisely so it reflects the sun and thus
appears as a bright dot, to another person 15 km. away, at an exact
time.

**Comment by brandon-rhodes** [comment]
That does sound like a challenge requiring precision! I would be tempted to investigate a slightly convex mirror, so that its angle would not have to be as precise, but maybe that would reduce the brightness too much since with a convex mirror only a small area would reflect light towards any one particular observer. Is my math correct that a mirror 1 foot wide appears, from 15 km, only 4 arcseconds across?

I'm not sure I've ever gone through the math of how much practical difference in position is produced by using one datum over another. If I ever get time to do such an investigation, I'll post back here with some ideas!

**Comment by drbitboy** [comment]
yah, I get 1ft÷15km ~ 4arcsec also

**Comment by jidanni** [comment]
Big bay windows are 99% more common than convex mirrors. 
https://www.jidanni.org/astro/reflections/index.html

**Comment by brandon-rhodes** [comment]
Wow! That's a bright window! I see now that the question is not theoretical for you but very practical. :)

**Comment by jidanni** [comment]
https://www.jidanni.org/astro/reflections/a-frame is an A-frame house
that, get this, changes color from red to white an hour a day.
Well, as you see in the links, at least I calculated why, within an hour
or so :-( .
