### ISSUE TITLE
The next base-60 frontier: timestamps

### ISSUE THREAD

**Issue by ludwigschwardt** [brandon-rhodes/pyephem#211]
Before:

```Python
In [1]: import ephem

In [2]: ephem.__version__
Out[2]: '3.7.7.1'

In [3]: ephem.Date('2019-02-11 02:10:47+00:00')
Out[3]: 43505.59082175926
```

Now:

```Python
In [1]: import ephem

In [2]: ephem.__version__
Out[2]: '4.0.0.1'

In [3]: ephem.Date('2019-02-11 02:10:47+00:00')
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-675418995a10> in <module>()
----> 1 ephem.Date('2019-02-11 02:10:47+00:00')

ValueError: invalid literal for float(): 47+00
```

**Comment by brandon-rhodes** [comment]
This one will be harder to decide! In your initial contribution 4abdae62d266fc8e8cb9eb319b6648d72a790481 you argued that PyEphem shouldn’t simply ignore noise in a string that it didn’t understand — “This replaces the previous relaxed behaviour where the string parsing always succeeds and invalid strings silently result in angles of 0.” So for me the big question here is whether 3.7.7.1 was using the string `+00:00` or whether it was silently ignoring and dropping it. If it was ignored, then I think that version 4 is here an improvement similar to the one you yourself made, since users will now for the first time understand that PyEphem doesn't understand or support appended time zones.

Could you do a quick additional 3.7.7.1 experiment? Try the same exercise but with other timezone, like `+01:00` or `-05:00` or somesuch, and see whether it affects the resulting timestamp. If so, then we'll definitely want to restore that behavior. But if the number is silently ignored, then I think the previous behavior was dangerous, similar to the behavior you fixed in your old diff?

**Comment by ludwigschwardt** [comment]
You're absolutely right... It's a mess 🤣 

```Python
In [57]: import ephem                                                                                         

In [58]: ephem.__version__                                                                                    
Out[58]: '3.7.7.0'

In [59]: print(ephem.Date('2019-02-11 12:34:56+00:00'))                                                       
2019/2/11 12:34:56

In [60]: print(ephem.Date('2019-02-11 12:34:56+01:00'))                                                       
2019/2/11 12:34:56

In [61]: print(ephem.Date('2019-02-11 12:34:56+02:00'))                                                       
2019/2/11 12:34:56

In [62]: print(ephem.Date('2019-02-11 12:34:56+03:00'))                                                       
2019/2/11 12:34:56

In [63]: print(ephem.Date('2019-02-11 12:34:56-00:00'))                                                       
2019/2/10 11:25:04

In [64]: print(ephem.Date('2019-02-11 12:34:56-01:00'))                                                       
2019/2/10 11:25:04

In [65]: print(ephem.Date('2019-02-11 12:34:56-02:00'))                                                       
2019/2/10 11:25:04
```

Good riddance!

**Comment by drbitboy** [comment]
LOL

**Comment by drbitboy** [comment]
>>> In [63]: print(ephem.Date('2019-02-11 12:34:56-00:00'))
>>> 2019/2/10 11:25:04        # <---- for the life of me, can't figure out this one...

the fields are processed left to right.  the negative sign flips the sign of the accumulating sum, which propagates to the left, so

2019/2/11 00:00:00 + (12:34:56) => 2019/2/**_10_** 11:25:04

**Comment by brandon-rhodes** [comment]
Thanks for doing some additional experiments! While I do recognize the chance of working code being turned into non-working code by the new version, I'm finding the previous behavior here unexpected enough that I think the library is stronger for not supporting it. This is uncharacteristic of me, since my sympathies lean more towards utter compatibility, but I'm going to click the Close button now and, I think, leave this stricter behavior in place.
