### ISSUE TITLE
Difference between sidereal time and right ascension of zenith

### ISSUE THREAD

**Issue by roe-dl** [brandon-rhodes/pyephem#219]
I read in an astronomy book, that sidereal time and right ascension of the zenith would have the same value. The same would apply to latitude and declination of zenith.

That short program
```
here = ephem.Observer()
here.lat, here.lon = '51', '13'
ra, dec = here.radec_of('0','90')
print("latitude longitude: %s %s" % (here.lat,here.lon))
print("declination: %s" % dec)
print("right ascension: %s" % ra)
print("sidereal time: %s" % here.sidereal_time())
```
results in
```
latitude longitude: 51:00:00.0 13:00:00.0
declination: 50:52:51.9
right ascension: 22:48:24.43
sidereal time: 22:49:19.97
```

There is a small difference between sidereal time and right ascension. And I do not understand why. Does someone know?

The result is independent of longitude.

**Comment by drbitboy** [comment]
leapseconds?

what is the time of ```here```?  What is the result if you force the time of ```here``` to be 2000-01-01T12:00:00?

**Comment by brandon-rhodes** [comment]
> I read in an astronomy book, that sidereal time and right ascension of the zenith would have the same value.

Which book? It would be helpful to see the exact claim that it's making, to know whether (for example) it's accounting for nutation in its assertion.

**Comment by drbitboy** [comment]
ooh, nutation, yeah.  Does the underlying XEphem package model that?  I know SPICE can.

Stellar aberration is another possibility, I suppose.

**Comment by roe-dl** [comment]
I would like to answer the questions within the different posts.

The book is "Grundlagen der Ephemeridenrechnung" by Oliver Montenbruck, ISBN 3-87973-941-2. It said on page 9: "Die Sternzeit 𝜃 ist die auf den momentanen Frühlingspunkt und Äquator bezogene Rektaszension des Zenitpunktes" (English: "Sidereal time 𝜃 is the right ascension of zenith in respect to the actual vernal point and equator.")

The timestamp of `here` is the actual date and time when the progam was run. The date was not set, so the default was used, so I think.

For `here.date = '2000-01-01 12:00:00'` the result is:
```
latitude longitude: 51:00:00.0 13:00:00.0
declination: 50:59:54.0
right ascension: 19:33:52.04
sidereal time: 19:33:49.70
```

First I wondered whether `here.radec_of('0','-90')[0]-sun.ra` or `here.sidereal_time()-sun.ra` ist the actual solar time. Both versions were suggested in the Internet. Then I found that `g_ra` instead of `ra` is used in `__init.py__` line 333 for calculation of the transit. So, in the end, I was a little bit confused.

**Comment by brandon-rhodes** [comment]
> English: "Sidereal time 𝜃 is the right ascension of zenith in respect to the actual vernal point and equator."

Thank you for the quote! We can now offer suggestions as to why those numbers do not match:

1. The book fails to mention that for computing LST you have to measure RA against the Earth’s poles and equinox of the current date. You cannot use the RA of another coordinate system like J2000.
2. PyEphem's documentation fails to mention that `.radec_of()` by default returns a J2000 RA and declination, unless you set `here.epoch` to some other date instead. (This is a big difference.)
3. PyEphem's documentation is in error when it says that `radec_of(az, alt)` “returns the apparent topocentric coordinates” — having just reviewed the code, it looks like it tries to return *astrometric* coordinates instead. (This is a much smaller difference.)

So by setting the `.epoch` of your `here`, you can make the angles agree fairly closely; but since you cannot turn off PyEphem’s conversion to astrometric coordinates, the number will still never quite agree with LST:

```
from __future__ import print_function
import ephem
from math import pi

to_hours = 12.0 / pi

here = ephem.Observer()
here.date = '2021-11-20 16:26'
here.lat, here.lon = '51', '13'
ra_j2000, _ = here.radec_of('0','90')

here.epoch = here.date
ra_eod, _ = here.radec_of('0','90')

print("Right Ascension, J2000:        ", ra_j2000 * to_hours)
print("Right Ascension, epoch of date:", ra_eod * to_hours)
print("Sidereal Time:                 ", here.sidereal_time() * to_hours)
```

Output:

```
Right Ascension, J2000:         21.2817844157
Right Ascension, epoch of date: 21.2939527091
Sidereal Time:                  21.2935713008
```

If we switch to a higher precision astronomy library that allows more options, like Skyfield, then we can see an RA that agrees far more closely with the corresponding LST. Here is a Skyfield script that shows the two numbers agreeing to very high precision, along with two quick illustrations of how PyEphem might be getting its numbers (with its approximate little corrections for apparent → astrometric):

```
from skyfield import api

ts = api.load.timescale()
t = ts.utc(2021, 11, 20, 16, 26)

location = api.wgs84.latlon(51, 13)
eph = api.load('de421.bsp')

# Skyfield agrees pretty closely with PyEphem about the LST, which is
# impressive given that PyEphem doesn't even know about leap seconds.

lst_hours = location.lst_hours_at(t)
print(lst_hours, 'Sidereal Time (LAST)')

# Now let's ask Skyfield for the apparent RA of the zenith.  The result
# agrees to very high precision with the LST, exactly as claimed by the
# book "Grundlagen der Ephemeridenrechnung".

observer = location.at(t)
apparent = observer.from_altaz(alt_degrees=90.0, az_degrees=0.0)
ra, dec, distance = apparent.radec(t)
print(ra.hours, 'Apparent RA of Zenith')

# So, where did the PyEphem RA come from?
#
# 1. A small difference: PyEphem `.radec_of()` doesn't return apparent
#    RA, but returns an (approximate) astrometric RA.  Skyfield doesn't
#    have a routine for going backwards from apparent to astrometric,
#    but we can ask Skyfield to make the same rough approximation that
#    PyEphem does.
#
# 2. A big difference: PyEphem `.radec_of()` by default returns J2000
#    coordinates instead of equinox-of-date, so the effect of nutation
#    is missing.  When we fail to apply nutation, we are measuring
#    against an entirely different celestial pole.
#
# Here is how to get similar numbers from Skyfield:

barycentric = (eph['Earth'] + location).at(t)

fake_star = api.Star(ra_hours=ra.hours, dec_degrees=dec.degrees)
fake_astrometric = barycentric.observe(fake_star)
fake_apparent = fake_astrometric.apparent()

ra1, _, _ = fake_astrometric.radec(t)
ra2, _, _ = fake_apparent.radec(t)
difference_between_astro_and_apparent = ra2.hours - ra1.hours

ra, _, _ = apparent.radec(t)
print(ra.hours - difference_between_astro_and_apparent,
      'Approximate astrometric RA (equinox of date)')

ra, _, _ = apparent.radec()
print(ra.hours - difference_between_astro_and_apparent,
      'Approximate astrometric RA (equniox J2000)')
```

Output:

```
21.293525326108064 Sidereal Time (LAST)
21.293525326298546 Apparent RA of Zenith
21.293641680442754 Approximate astrometric RA (equinox of date)
21.281727387687614 Approximate astrometric RA (equniox J2000)
```

I will update PyEphem’s quick reference to be clearer about the quantities that these routines return.

**Comment by brandon-rhodes** [comment]
There — I have updated the PyEphem Quick Reference to offer far better descriptions of `.sidereal_time()` and `.radec_of()` that hopefully make the above distinctions much more clear. Please comment with any questions you have about my comment above or about the new documentation; the diff is at:

2a83f524ff903146981c588e78bbda0823bd3dbe

Thanks for the question, it pointed out several things that needed to be fixed in the Quick Reference!

**Comment by roe-dl** [comment]
Thank you very much for your detailed answer and clarifications. That helped a lot.
