### ISSUE TITLE
Calculating moon's next transit changes moon phase result

### ISSUE THREAD

**Issue by aaronwmorris** [brandon-rhodes/pyephem#227]
I am not sure if this is a bug or a feature.

OS:  Raspbian 10
Python: 3.7.3
Hardware:  armv7l
ephem:  4.1.3

Test script
```
#!/usr/bin/env python3

import ephem
import datetime
import math
import logging

logging.basicConfig(level=logging.INFO)
logger = logging


utcnow = datetime.datetime.utcnow()

obs = ephem.Observer()
obs.lat = math.radians(33)
obs.lon = math.radians(-84)
obs.date = utcnow

moon = ephem.Moon()
moon.compute(obs)

logger.info('Moon phase: %0.2f%%', moon.moon_phase * 100)

logger.info('Next Transit: %s', obs.next_transit(moon))

logger.info('Moon phase: %0.2f%%', moon.moon_phase * 100)
```

Results in
```
INFO:root:Moon phase: 55.06%
INFO:root:Next Transit: 2022/2/10 00:35:41
INFO:root:Moon phase: 63.72%
```

**Comment by brandon-rhodes** [comment]
That is what the Quick Reference means when it says that the transit routines “Always leaves the Body at its position on that date” — it means that after the search, the body still has the `.date` of the transit — so that its right ascension, and declination, and moon phase, and everything else, will be for that new date.

Is there a way I can improve how the Quick Reference says that to make it clearer and prevent confusion?

**Comment by aaronwmorris** [comment]
As long as that is the intended/documented behavior, it is fine with me.  I did find that setting the `.date` back did correct the behavior.
