### ISSUE TITLE
How to display all objects

### ISSUE THREAD

**Issue by portisum** [brandon-rhodes/pyephem#241]
Hi, how do I make pyehem show all the planets stars asteroids etc to be displaced for a specific moment all at one?
like I want everything in the catalogue for 12.11.2019 13:45 Prague
W

**Comment by Bernmeister** [comment]
When you say _show_, are you wanting a visual display of planets/stars?  If so, then perhaps try something like [Stellarium Web](https://stellarium-web.org/) off the top of my head.

Otherwise, to compute just raw the numbers (positions and rise/set), take a look at the [documentation](https://rhodesmill.org/pyephem).  There is an example at the top of the page and further detail in you dive into the table of contents.

**Comment by portisum** [comment]
noooo
We need placements in a natal chart

**Comment by portisum** [comment]
I dunno can I place a pic in here - but if not just google what the natal chart is - and do you think I don’t know stellarium exists?

**Comment by brandon-rhodes** [comment]
> do you think I don’t know stellarium exists?

@portisum, your question about how to “show” planets and stars sounded exactly like you were asking for a visual display. I think it was entirely reasonable for @Bernmeister to refer you to Stellarium—a very nice tool that I use myself and which, no, not everyone knows about; I have recently introduced people to the tool myself, and it was new to them. Why would we think that you were any different from them?

Also, PyEphem contributors tend to be busy people, and asking them to take their own time to Google resources that you could much more easily provide is a poor use of time. Not only do _n_ people have to go searching for the same thing to understand what is being asked in the issue, but there's no guarantee that what comes up in their search is exactly what you are asking for, which can cause confusion and waste time. (I have seen it happen!) Becaues you are the expert here on what you are asking, you are the best person to provide an example or chart.

So, for this issue to proceed, I think you should provide a screenshot or printout of what kind of calculation you are asking about.

**Comment by brandon-rhodes** [comment]
(Oh: and, yes, you can place a picture here! Just select the image on your computer, select "Copy image" (for example with a right-click in your web browser), and then return to a comment you are writing here and paste with Ctrl-V.)

**Comment by portisum** [comment]
Hi! Its just very popular by my understanding - sorry for the inconvenience but like everyone love the sky so I thought u were a lil bit like rude but no problem if u put it like that - I take my words back! 

Im sorry I am super new to python and its kinda hard for me - my guys from python chat said to write to the library sorsce - Okay I think I will go with easier option than so it would be quicker cuz I can display them into a natal chart after I do this

How do I display all the objects in catalogue at once?
Like sun is here
Moon is here
Mars is here
…
Tom Hanks
Asteroid 24090
Ganymede is here

Because there are 5mil of asteroids in space do I like print all the names??

**Comment by brandon-rhodes** [comment]
> like everyone love the sky so I thought u were a lil bit like rude … I take my words back!

Thank you. I am still not sure what looked rude about @Bernmeister’s words, but I believe he was trying to be helpful, and not to insult anyone for not knowing about Stellarium.

> How do I display all the objects in catalogue at once?

You will want to use a Python list, I think. Ask on the Python chat how to loop through the lines in a file, since in an ephem-format asteroid file there will be one asteroid per line. Then, for each line, use `readdb()` to create a new PyEphem body object, and add it to a list. Here's its documentation:

https://rhodesmill.org/pyephem/quick.html#catalog-format

Then, you can loop across the list of bodies, and `print` the name of each one.
