### ISSUE TITLE
Calculate position of north and the south lunar

### ISSUE THREAD

**Issue by code4passion** [brandon-rhodes/pyephem#273]
How can we calculate position of north and the south lunar nodes?

In hindu mythology rahu (north lunar node) and kethu (south lunar nodes) are considered as major celestial bodies. How can i calculate their position?
https://en.wikipedia.org/wiki/Rahu

What will be accurate dimension to represent it? Lat/Long? or something else. Pardon my lack of knowledge here.

**Comment by brandon-rhodes** [comment]
Alas, PyEphem doesn't, as far as I know, provide any mechanism for computing those. Do you know how the ancients did it? My suggestion would be to read their ancient guides to computing the nodes. Did they, for example, assume that the nodes moved uniformly along the ecliptic over the weeks between actual visits of the Moon to the ecliptic? Once you know how the original Hindus computed them, simply do the same thing they did: ask PyEphem for the dates and times and ecliptic longitudes of the Moon's ascending nodes and descending nodes, and then interpolate the fake positions in between the actual nodes in order to have continuous positions on the intervening dates for rahu and kethu.

(You could also search online for formulae? But maybe you've already done that and didn't find anything useful.)

**Comment by drbitboy** [comment]
You could use the Geometry Finder tool of NAIF/SPICE (see naif.jpl.nasa.gov) to determine when the Moon's Earth- or Sun-, relative position's Z coordinate in the ECLIPJ2000 frame is 0.
