### ISSUE TITLE
Pyephem seems to compute wrong range_velocity

### ISSUE THREAD

**Issue by Box88** [brandon-rhodes/pyephem#34]
I am comparing the results from satellite trackers (e.g. Gpredict, Orbitron) and pyephem results. The range is the same but the range_velocity is different. Any idea?

**Comment by alexschultze** [comment]
Has there any progress on the discrepancy between xephem and gpredict? Possibly the difference is caused by the fact that Xephem uses atmospheric fraction for its prediction. (So maybe its a feature?)

http://stackoverflow.com/questions/23551019/range-rate-for-doppler-calculation-and-atmospheric-refraction-compensation?rq=1
