### ISSUE TITLE
Passes over an Area of Interest (AoI)

### ISSUE THREAD

**Issue by rtubio** [brandon-rhodes/pyephem#78]
Dear all,

I keep working on this project for the network of ground stations and I am now trying to calculate the passes of a given satellite not over a ground station, but over an area of interest (AoI). It is problem that might look like equivalent beforehand to the calculation of the passes over a ground station, but I think that the current calculation capacities of PyEphem cannot be directly used for this new feature.

Therefore, my question is: does it exist any documentation about the internals of PyEphem? I have been reading in the website that it uses XEphem internally, should I take a look at that library instead?

Best, Ricardo.

**Comment by brandon-rhodes** [comment]
Since no contributors have answered over the past six years, and since PyEphem inconveniently fails to expose the underlying vectors that would make calculations convenient, I'm going to close this issue. I recommend trying out Skyfield, which does expose all the vectors underlying its calculations, and might make an area-of-interest routine easier to write.
