### ISSUE TITLE
Clarify units of lat/lon based on type for Observer in docstring

### ISSUE THREAD

**Issue by 153957** [brandon-rhodes/pyephem#90]
Recently I, and also a colleague of mine, stumbled across the unclear units for lat/lon for Observers.

```
float - radians.
string - degrees (in decimal or sexagesimal notation).
```

I found we were not the only ones surprised by this.
http://stackoverflow.com/questions/15639949

A few lines in the Observer docstring tho explain this would be great.

**Comment by brandon-rhodes** [comment]
I will expand the docstring in the next version of PyEphem to try to make this clearer. Thanks for the idea!

**Comment by bmxp** [comment]
I ran into some trouble when I read the inline documentation of ephem with python help().
Enter ``help(ephem.Observer())`` on a Python prompt and the result will contain the following:

```
class Observer(_libastro.Observer)
 |  A location on earth for which positions are to be computed.
 |
 |  An `Observer` instance allows you to compute the positions of
 |  celestial bodies as seen from a particular latitude and longitude on
 |  the Earth's surface.  The constructor takes no parameters; instead,
 |  set its attributes once you have created it.  Defaults:
 |
 |  `date` - the moment the `Observer` is created
 |  `lat` - zero degrees latitude
 |  `lon` - zero degrees longitude
 |  `elevation` - 0 meters above sea level
 |  `horizon` - 0 degrees
 |  `epoch` - J2000
 |  `temp` - 15 degrees Celsius
 |  `pressure` - 1010 mBar
 
.... and later at the end:

 |   lat
 |      Latitude north of the Equator as a float giving radians, or a string giving degrees:minutes:seconds
 |
 |  lon
 |      Longitude east of Greenwich as a float giving radians, or a string giving degrees:minutes:seconds
 |
 |  long
 |      Longitude east of Greenwich as a float giving radians, or a string giving degrees:minutes:seconds
 ```
The top of the help() shows that lat, long are initialized as zero **degrees** while the bottom description writes about **radians**. 
Since using degrees to specify an observer yields the correct sunrise/sunset etc. upon compute() this would lead me to the idea that the lower description to provide radians might not be correct ...

**Comment by brandon-rhodes** [comment]
Returning to this issue during a New Year review of my dashboard: I think the word "degrees" in that summary is indeed misleading about the units involved, so I've just landed a fix to remove it.
